---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ11N18"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false
  Compliance:
    sonarExecuteScan: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
    cfOrg: "gartner-lcap-mq"
    cfSpace: "prod"
    cfCredentialsId: "my-credential"
    tmsUpload: false
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: ""
    credentialsId: ""
