/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const reorder_Store_Logic = require('./code/reorder-store-logic');

class storeInventorySrv extends LCAPApplicationService {
    async init() {

        this.on('READ', 'Store', async (request, next) => {
            await reorder_Store_Logic(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    storeInventorySrv
};